### ISSUE TITLE
Datasets issue

### ISSUE THREAD

**Issue by Quyangya** [rtarun9/HFormer-Low-Dose-CT-Denoiser#1]
Could you please tell me how to obtain the data set of this paper? I have found a lot of channels on the Internet. Could you please provide the data set?

**Comment by rtarun9** [comment]
@Quyangya you can find the dataset (partial) here : https://aapm.app.box.com/s/eaw4jddb53keg1bptavvvd1sf4x3pe9h.

To access the full dataset (which sums up to 1TB) you can get it here (https://www.cancerimagingarchive.net/collection/ldct-and-projection-data/), however you do need to fill and submit a form.

**Comment by rtarun9** [comment]
@Quyangya , I have added the partial and full dataset download links to the README.md page. If there are more issues you are facing with respect to acquiring the dataset, do let me know. If not, I will be closing this issue soon 😄
